### ISSUE TITLE
Install is skipped on Arm64

### ISSUE THREAD

**Issue by vyas-n** [geerlingguy/ansible-role-go#3]
I'm trying to use this Ansible Role to install golang version `1.19.4` into an Ubuntu 20.04 Docker container.

For it I have an Amd64 version and an Arm64 version. The Amd64 version installs successfully, but the Arm64 version skips the entire installation process.

Ansible Playbook
```yaml
---
- name: Provision Dev Image
  hosts: localhost
  connection: local
  roles:
    # Install latest golang from: https://go.dev/dl
    - role: geerlingguy.go
      become: true
      vars:
        go_version: 1.19.4
        go_arch: amd64
        go_checksum: c9c08f783325c4cf840a94333159cc937f05f75d36a8b307951d5bd959cf2ab8
      when: ansible_architecture == "x86_64"
    - role: geerlingguy.go
      become: true
      vars:
        go_version: 1.19.4
        go_arch: arm64
        go_checksum: 9df122d6baf6f2275270306b92af3b09d7973fb1259257e284dba33c0db14f1b
      when: ansible_architecture == "arm64"
```

Ansible Galaxy Requirements:
```yaml
---
roles:
  - name: geerlingguy.go
    version: 1.1.0
  - name: geerlingguy.nodejs
    version: 6.1.1
```

[build.log](https://github.com/geerlingguy/ansible-role-go/files/10353385/build.log)
