### ISSUE TITLE
Go Checksum

### ISSUE THREAD

**Issue by thegreatestgiant** [geerlingguy/ansible-role-go#4]
The Go Checksum only works for your specific version
I think it would be better if you could automate it so I asked chatgpt and he gave me this
```yaml
---
- name: Query JSON data from URL and extract checksum
  hosts: localhost  # You can specify the target host(s) here
  gather_facts: false  # We don't need to gather facts for this task
  tasks:
    - name: Fetch JSON data from URL
      uri:
        url: "https://go.dev/dl/?mode=json"
        method: GET
        return_content: yes
      register: response

    - name: Parse JSON data
      set_fact:
        json_data: "{{ response.json }}"

    - name: Extract checksum for a specific version
      set_fact:
        version_to_query: "go1.17.3"  # Replace with the version you want to query
        checksum: "{{ json_data.versions[version_to_query].checksum }}"
      when: version_to_query in json_data.versions

    - name: Display checksum
      debug:
        var: checksum
```
I'd appreciate it if you could incorporate something like this into the role and also update the GO version

There probably is a better way to query it but I can't find the correct queries and don't know where to look, all I have is `https://go.dev/dl/?mode=json`
